//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Тестирование
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoPlayer
    {
        public int Id_info { get; set; }
        public int id_достижения { get; set; }
        public int Id_игрока { get; set; }
        public bool Наличие { get; set; }
    
        public virtual Registration Registration { get; set; }
        public virtual Достижения Достижения { get; set; }
    }
}
